### ISSUE TITLE
isNull(ISSUE) doesn't work

### ISSUE THREAD

**Issue by MattBlissett** [gbif/gbif-predicates#6]
This should result in a `issue IS NULL OR size(issue) = 0` predicate, but it only tests for null, and the array is empty rather than null.

**Comment by MattBlissett** [comment]
It was this error this morning:

```
Caused by: java.lang.NullPointerException
	at brickhouse.udf.collect.JoinArrayUDF.evaluate(JoinArrayUDF.java:42)
	at brickhouse.udf.collect.JoinArrayUDF.evaluate(JoinArrayUDF.java:55)
	at org.apache.hadoop.hive.ql.udf.generic.GenericUDF.initializeAndFoldConstants(GenericUDF.java:174)
```

and part of the generated query predicate was `(issue IS NULL )` which I guessed was the problem.

https://www.gbif.org/occurrence/download/0194643-220831081235567
